name: Check

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker Build
        run: |
          mkdir bin
          cp -rf ./wrtbwmon ./bin/
          docker pull ghcr.io/openwrt/sdk:tegra-generic-24.10-snapshot
          docker run --rm -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin -v ${{ github.workspace }}/.github/workflows:/home/build/workflows ghcr.io/openwrt/sdk:tegra-generic-24.10-snapshot /bin/sh /home/build/workflows/build.sh
      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./bin/packages/x86_64/base/wrtbwmon*
      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: bin/logs.tar.xz

